# Generated by Django 4.2.5 on 2023-09-05 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_bid_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="auction_watchers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="CategoryID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auction_category",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="UserID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auction_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="AuctionID",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_auction",
                to="auctions.auction",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="UserID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_bidder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="AuctionID",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_auction",
                to="auctions.auction",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="UserID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comment_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
