# Generated by Django 4.2.5 on 2023-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_auction_watchers_alter_auction_categoryid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="IsStarting",
            field=models.BooleanField(default=True),
        ),
    ]
