# Generated by Django 4.2.5 on 2023-10-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_post_likedby_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="message",
            field=models.CharField(default="One off default", max_length=150),
            preserve_default=False,
        ),
    ]
